Fixed a conflict with libiconv and pkg-config
Libiconv has to be installed before pkg-config otherwise there
would be a compilation error:

gconvert.c:61:2: error: #error GNU libiconv not in use but included
iconv.h is from libiconv
    61 | #error GNU libiconv not in use but included iconv.h is from
libiconv